package config

const (
	LEADER_TIMEOUT          = 5
	LEADER_PING_INTERVAL    = 2
	ELECTION_TIMEOUT        = 200
	ELECTION_TIMEOUT_JITTER = 200

	COMMIT_INTERVAL              = 5 //sec
	STATE_MACHINE_APPLY_INTERVAL = 5 // sec

	UPDATE_COMMIT_INTERVAL = 5 //sec

	STATUS_LOGGING_TIME_INTERVAL = 1
)
